### ISSUE TITLE
RAPIDS support discontinued for systems running OS versions lower than Ubuntu 20.04 or Rocky Linux 8

### ISSUE THREAD

**Issue by quail768** [EliHei2/segger_dev#14]
Hi, Cool tool! I'd like to try this with CUDA12 and RAPIDS support. However it appears that that the cudf-cu12 version which is required by segger which is 24.8 can't be installed on OSs with Ubuntu 18.04 or below with glibc 2.17 as stated here:https://github.com/rapidsai/cudf/issues/16804#issuecomment-2351092184

 I tried installing a local glibc v2.31 but it doesn't seem to fix this issue

I work on a computing cluster with REHL Fedora where the default version OS version is glibc 2.17. So I can't upgrade the OS unfortunately.

The main installation works fine. However this seems to be a little complicated. Any thoughts on potential work-arounds or would you suggest to go ahead without CUDA and RAPIDS support?

**Comment by EliHei2** [comment]
hey @quail768 thanks for posting the issue, we're aware of this issue as also mentioned by in #9 and are working on it to get a stable installation of rapids, for the current release, rapids is not necessary to get through the pipeline. For the next releases that would highly depend on RAPIDS, we make sure to provide proper installation instructions and/or a docker container. pining @andrewmoorman to be aware.

Anyways, you might have success by `pip install cu{df/vs/graph/ml}-cu12==24.4.* --no-cache-dir`

**Comment by quail768** [comment]
Gotcha thanks @EliHei2. I was able to use a container and the installation for RAPIDS works fine now! 

I also had a question about the cell type abundance embedding. Is that required or is it optional? How much does adding the cell type abundance embedding affect the final output?

**Comment by EliHei2** [comment]
@quail768 glad that it solved the problem, we're gonna contact RAPIDS people to fix the installation issue. I redirected the other question to a new issue and gonna answer soon! I close this one.
