### ISSUE TITLE
[BUG] If num_workers > 1, data processing skips a significant number of tiles.

### ISSUE THREAD

**Issue by daniel-unyi-42** [EliHei2/segger_dev#27]
It's a severe issue, using multiple workers drastically improves data processing times, but something is preventing the parallelized processes from completing.

To reproduce, set n_workers > 1 in `STSampleParquet`.

**Comment by EliHei2** [comment]
This is weird, I'll have a look. @andrewmoorman do you have an idea why it could be the case?!

**Comment by LucaMarconato** [comment]
Hi, reporting here because it seems related, but if not please feel free to move this comment in a separate issue. I also experienced `segger` getting stuck when setting `n_workers > 1`. 

To reproduce I used this small Xenium dataset (the 11.9 MB one): https://www.10xgenomics.com/support/software/xenium-onboard-analysis/latest/resources/xenium-example-data and I used this code:

```python
from segger.data.io import XeniumSample
from segger.training.train import LitSegger
from segger.training.segger_data_module import SeggerDataModule
from segger.prediction.predict import predict, load_model
from lightning.pytorch.loggers import CSVLogger
from pytorch_lightning import Trainer
from pathlib import Path
from lightning.pytorch.plugins.environments import LightningEnvironment
from matplotlib import pyplot as plt
import seaborn as sns

# Paths to Xenium sample data and where to store Segger data
xenium_data_dir = Path('data/Xenium_Prime_MultiCellSeg_Mouse_Ileum_tiny_outs')
segger_data_dir = Path('data/segger_data/')

# Setup Xenium sample to create dataset
xs = XeniumSample(verbose=False)
xs.set_file_paths(
    transcripts_path=xenium_data_dir / 'transcripts.parquet',
    boundaries_path=xenium_data_dir / 'nucleus_boundaries.parquet',
)
xs.set_metadata()

# for i in range(50):
    
import shutil
import os

if segger_data_dir.exists() and 'segger_data' in str(segger_data_dir):
    shutil.rmtree(str(segger_data_dir))

try:
    xs.save_dataset_for_segger(
        processed_dir=segger_data_dir,
        r_tx=5,
        k_tx=15,
        x_size=120,
        y_size=120,
        d_x=100,
        d_y=100,
        margin_x=10,
        margin_y=10,
        scale_boundaries=1,
        num_workers=1,  # change to you number of CPUs
        # val_prob=0.5,
    )
except AssertionError as err:
    print(f'Dataset already exists at {segger_data_dir}')
```

After a few iterations, the progressbar gets stuck. This doesn't happen if I set `num_workers=0`. 
CC @EliHei2 (we spotted this together).

**Comment by quail768** [comment]
Heya I've been facing this issue as well. Don't think its a memory issue as I reserved the same amount of memory when I run this on 1 CPU compared to 10 CPUs. It finishes till about 2-3 percent before it stalls perpetually when running with 10 CPUs. When I run it on 1 CPU it completes to the end in a very short time.

**Comment by andrewmoorman** [comment]
Hi @quail768! Is the issue you mentioned when using the STSampleParquet class or the XeniumSample class?
