### ISSUE TITLE
Segger Similarity Score Histogram

### ISSUE THREAD

**Issue by quail768** [EliHei2/segger_dev#32]
Hello, 
Not so much a bug but a general question about the histogram. I have a model trained and I used the predict function and generated the Segger Similarity score histogram. 

![image](https://github.com/user-attachments/assets/b6ea856f-66bc-4300-b1d6-75f1d1449423)

Would you be happy with the histogram or would  it need parameter tuning? Because there is a clear peak for high quality but there is also a large number of scores near 0.

The model training went well I think
![image](https://github.com/user-attachments/assets/ba90c5ac-82bb-44d2-b28e-a7b6d9c32149)

What do you think?

**Comment by EliHei2** [comment]
Based on my experience, this looks good. However, one should decide on the optimal set of parameters, only based on the biology of segmented cells. Let me know how the final results look like based on the biology in hand.

**Comment by quail768** [comment]
Sounds good! Unfortunately the segmentation is crashing with the new additions at src/segger/data/parquet/pyg_dataset.py 😅Opening a new issue

**Comment by quail768** [comment]
![image](https://github.com/user-attachments/assets/53a1a1f6-0847-4872-a803-46b92eb98a46)
@EliHei2 I ran a predict on unseen data using the model trained as above. I'm not sure if this is expected. Do you think something is wrong or is the model performing well?

**Comment by quail768** [comment]
1) The model is trained on the same tissue yes.
2) The tissues were on the same Xenium slide so yes the panel is the same.

3) I just ran the predict function. The model was trained using the following params: 
aggr: sum
heads: 2
hidden_channels: 32
init_emb: 8
metadata: !!python/tuple
- - tx
  - bd
- - !!python/tuple
    - tx
    - belongs
    - bd
  - !!python/tuple
    - tx
    - neighbors
    - tx
num_mid_layers: 2
num_tx_tokens: 500
out_channels: 8

```
receptive_field = {'k_bd': 4, 'dist_bd': 12,'k_tx': 15, 'dist_tx': 3}

# Perform segmentation (predictions)
segmentation = predict(
    model,
    dm.train_dataloader(),
    score_cut=0.33,  
    receptive_field=receptive_field,
    use_cc=False,
)
```
4) The sample used for training had about 250,000 cells.
The sample used for  performing the above prediction had 125,000 cells.

**Comment by EliHei2** [comment]
Everything seems normal, I personally have not experienced this. maybe @andrewmoorman or @daniel-unyi-42  did?
the bottom-line is the biology you get out of your segmentation, if it makes sense.
