### ISSUE TITLE
Change cagra.build_index to cagra.build

### ISSUE THREAD

**Issue by quail768** [EliHei2/segger_dev#33]
**Describe the issue with the current implementation**
Currently the segment function at src/segger/data/utils.py on line 400 has the old cagra.build_index command. 

This has been replaced by cagra.build as mentioned here:https://github.com/rapidsai/cuvs/pull/187#issue-2351731671 and so it gives the following error when the segment funtion is run:

AttributeError: module 'cuvs.neighbors.cagra' has no attribute 'build_index'

**Suggested improvement**
Maybe would just change that?

**Additional context**
Any other context or screenshots that might help clarify the issue.

**Comment by EliHei2** [comment]
@quail768 very good pick. We've been struggling with cuvs and in general rapids versions, it's on our to-do list to find a stable solution for this. thanks for letting us know.

**Comment by daniel-unyi-42** [comment]
@quail768 should work now with any version!
