### ISSUE TITLE
[BUG] duplicate test

### ISSUE THREAD

**Issue by LucaMarconato** [EliHei2/segger_dev#35]
The test `test_filter_transcripts()` appear twice in `test_data.py`: https://github.com/EliHei2/segger_dev/blob/9ae16c7f3a28781d64b11b0bb8d2c1ce91bd0fd1/tests/test_data.py#L12 https://github.com/EliHei2/segger_dev/blob/9ae16c7f3a28781d64b11b0bb8d2c1ce91bd0fd1/tests/test_data.py#L59

The second test fails because `XeniumSample` is not imported.

**Comment by EliHei2** [comment]
yes, the tests are from ages ago, we're gonna add some tests. @daniel-unyi-42 could you please update and add some tests once the end-to-end CLI is done?

**Comment by EliHei2** [comment]
tests are gonna be re-written in v0.1.1.
