### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by quail768** [EliHei2/segger_dev#59]
---

name: Bug Report
about: TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
title: "[BUG] "
labels: bug
assignees: ''

---

**Describe the bug**
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**To Reproduce**
```
from segger.data.io import XeniumSample
from segger.training.train import LitSegger
from segger.training.segger_data_module import SeggerDataModule
from segger.prediction.predict import predict, load_model, segment
from lightning.pytorch.loggers import CSVLogger
from pytorch_lightning import Trainer
from pathlib import Path
from lightning.pytorch.plugins.environments import LightningEnvironment
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

# Paths to Xenium sample data and where to store Segger data
xenium_data_dir = Path('/mnt/N5_T2/Xenium_Exp')
segger_data_dir = Path('/mnt/N5_T2/segger/')

# Setup Xenium sample to create dataset
xs = XeniumSample(verbose=False)
xs.set_file_paths(
    transcripts_path=xenium_data_dir / 'transcripts.parquet',
    boundaries_path=xenium_data_dir / 'nucleus_boundaries.parquet',
)
xs.set_metadata()

models_dir = Path('/mnt/models')
# Checkpoint directory for Lightning model above
model_version = 5

# Load in latest checkpoint
model_path = models_dir / 'lightning_logs' / f'version_{model_version}'
model = load_model(model_path / 'checkpoints')
dm = SeggerDataModule(
    data_dir=segger_data_dir,
    batch_size=2,  
    num_workers=0,  
)
dm.setup()
save_directory=Path('/mnt/N5_T2/segout')
segmentation_tag = 'N5_T2'  
transcript_file_path = Path('/mnt/N5_T2/Xenium_Exp/transcripts.parquet')  
score_cutoff = 0.5  
# Optional parameters
file_format = 'anndata'  
use_connected_components = False 
knn_algorithm = 'kd_tree' 
verbose_output = True  

# Receptive field configuration
receptive_field_config = {'k_bd': 4, 'dist_bd': 12, 'k_tx': 15, 'dist_tx': 3}

# Call the `segment` function
segment(
    model=model, 
    dm=dm, 
    save_dir=save_directory, 
    seg_tag=segmentation_tag, 
    transcript_file=transcript_file_path, 
    score_cut=score_cutoff, 
    use_cc=use_connected_components, 
    file_format=file_format, 
    receptive_field=receptive_field_config, 
    knn_method=knn_algorithm, 
    verbose=verbose_output
)
```

**Expected behavior**
Segmentation Completes to the end

**Screenshots or logs**
```
INFO:  
Traceback (most recent call last):
  File "/Segger/Segment.py", line 46, in <module>
    segment(
  File "/segger_dev/src/segger/prediction/predict.py", line 493, in segment
    segmentation_train = predict(model, train_dataloader, score_cut, receptive_field, use_cc, knn_method)
  File "/segger_dev/src/segger/prediction/predict.py", line 365, in predict
    assignments = predict_batch(lit_segger, batch, score_cut, receptive_field, use_cc, knn_method)
  File "/segger_dev/src/segger/prediction/predict.py", line 231, in predict_batch
    scores = get_similarity_scores(lit_segger.model, batch, "tx", "bd", receptive_field, knn_method=knn_method)
  File "/segger_dev/src/segger/prediction/predict.py", line 130, in get_similarity_scores
    edge_index = get_edge_index(
  File "/segger_dev/src/segger/data/utils.py", line 291, in get_edge_index
    return get_edge_index_kdtree(coords_1, coords_2, k=k, dist=dist, workers=workers)
  File "/segger_dev/src/segger/data/utils.py", line 317, in get_edge_index_kdtree
    tree = cKDTree(coords_1)
  File "_ckdtree.pyx", line 557, in scipy.spatial._ckdtree.cKDTree.__init__
  File "/segger/lib/python3.10/site-packages/torch/_tensor.py", line 1085, in __array__
    return self.numpy().astype(dtype, copy=False)
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

**Environment (please complete the following information):**

-OS: Ubuntu 22.04
-Python version: 3.10
- Package version:

> _libgcc_mutex             0.1                 conda_forge    conda-forge
> _openmp_mutex             4.5                       2_gnu    conda-forge
> adjusttext                1.2.0                    pypi_0    pypi
> aiohappyeyeballs          2.4.3                    pypi_0    pypi
> aiohttp                   3.10.10                  pypi_0    pypi
> aiosignal                 1.3.1                    pypi_0    pypi
> anndata                   0.10.9                   pypi_0    pypi
> array-api-compat          1.9                      pypi_0    pypi
> asciitree                 0.3.3                    pypi_0    pypi
> async-timeout             4.0.3                    pypi_0    pypi
> attrs                     24.2.0                   pypi_0    pypi
> bounded-pool-executor     0.0.3                    pypi_0    pypi
> bzip2                     1.0.8                h4bc722e_7    conda-forge
> ca-certificates           2024.8.30            hbcca054_0    conda-forge
> certifi                   2024.8.30                pypi_0    pypi
> charset-normalizer        3.4.0                    pypi_0    pypi
> click                     8.1.7                    pypi_0    pypi
> cloudpickle               3.1.0                    pypi_0    pypi
> contourpy                 1.3.0                    pypi_0    pypi
> cuda-python               12.6.0                   pypi_0    pypi
> cupy-cuda12x              13.3.0                   pypi_0    pypi
> cuvs-cu12                 24.4.0                   pypi_0    pypi
> cycler                    0.12.1                   pypi_0    pypi
> dask                      2024.9.0                 pypi_0    pypi
> dask-cuda                 24.10.0                  pypi_0    pypi
> dask-expr                 1.1.14                   pypi_0    pypi
> dask-geopandas            0.4.2                    pypi_0    pypi
> dask-image                2024.5.3                 pypi_0    pypi
> distributed               2024.9.0                 pypi_0    pypi
> docrep                    0.3.2                    pypi_0    pypi
> exceptiongroup            1.2.2                    pypi_0    pypi
> faiss-cpu                 1.9.0                    pypi_0    pypi
> faiss-gpu                 1.7.2                    pypi_0    pypi
> fasteners                 0.19                     pypi_0    pypi
> fastrlock                 0.8.2                    pypi_0    pypi
> filelock                  3.16.1                   pypi_0    pypi
> fonttools                 4.54.1                   pypi_0    pypi
> frozenlist                1.4.1                    pypi_0    pypi
> fsspec                    2024.9.0                 pypi_0    pypi
> geopandas                 1.0.1                    pypi_0    pypi
> h5py                      3.12.1                   pypi_0    pypi
> idna                      3.10                     pypi_0    pypi
> igraph                    0.11.6                   pypi_0    pypi
> imageio                   2.35.1                   pypi_0    pypi
> importlib-metadata        8.5.0                    pypi_0    pypi
> inflect                   7.4.0                    pypi_0    pypi
> jinja2                    3.1.4                    pypi_0    pypi
> joblib                    1.4.2                    pypi_0    pypi
> kiwisolver                1.4.7                    pypi_0    pypi
> lazy-loader               0.4                      pypi_0    pypi
> ld_impl_linux-64          2.43                 h712a8e2_1    conda-forge
> legacy-api-wrap           1.4                      pypi_0    pypi
> leidenalg                 0.10.2                   pypi_0    pypi
> libffi                    3.4.2                h7f98852_5    conda-forge
> libgcc                    14.1.0               h77fa898_1    conda-forge
> libgcc-ng                 14.1.0               h69a702a_1    conda-forge
> libgomp                   14.1.0               h77fa898_1    conda-forge
> libnsl                    2.0.1                hd590300_0    conda-forge
> libsqlite                 3.46.1               hadc24fc_0    conda-forge
> libuuid                   2.38.1               h0b41bf4_0    conda-forge
> libxcrypt                 4.4.36               hd590300_1    conda-forge
> libzlib                   1.3.1                hb9d3cd8_2    conda-forge
> lightning                 2.4.0                    pypi_0    pypi
> lightning-utilities       0.11.7                   pypi_0    pypi
> llvmlite                  0.43.0                   pypi_0    pypi
> locket                    1.0.0                    pypi_0    pypi
> markupsafe                3.0.1                    pypi_0    pypi
> matplotlib                3.9.2                    pypi_0    pypi
> matplotlib-scalebar       0.8.1                    pypi_0    pypi
> more-itertools            10.5.0                   pypi_0    pypi
> mpmath                    1.3.0                    pypi_0    pypi
> msgpack                   1.1.0                    pypi_0    pypi
> multidict                 6.1.0                    pypi_0    pypi
> natsort                   8.4.0                    pypi_0    pypi
> ncurses                   6.5                  he02047a_1    conda-forge
> networkx                  3.4.1                    pypi_0    pypi
> numba                     0.60.0                   pypi_0    pypi
> numcodecs                 0.13.1                   pypi_0    pypi
> numpy                     1.26.4                   pypi_0    pypi
> nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
> nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
> nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
> nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
> nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
> nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
> nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
> nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
> nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
> nvidia-nvjitlink-cu12     12.6.77                  pypi_0    pypi
> nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
> omnipath                  1.0.8                    pypi_0    pypi
> openssl                   3.3.2                hb9d3cd8_0    conda-forge
> packaging                 24.1                     pypi_0    pypi
> pandas                    2.2.3                    pypi_0    pypi
> partd                     1.4.2                    pypi_0    pypi
> path                      17.0.0                   pypi_0    pypi
> patsy                     0.5.6                    pypi_0    pypi
> pillow                    10.4.0                   pypi_0    pypi
> pims                      0.7                      pypi_0    pypi
> pip                       24.2               pyh8b19718_1    conda-forge
> pqdm                      0.2.0                    pypi_0    pypi
> propcache                 0.2.0                    pypi_0    pypi
> psutil                    6.0.0                    pypi_0    pypi
> pyarrow                   16.1.0                   pypi_0    pypi
> pylibraft-cu12            24.4.0                   pypi_0    pypi
> pynndescent               0.5.13                   pypi_0    pypi
> pynvml                    11.4.1                   pypi_0    pypi
> pyogrio                   0.10.0                   pypi_0    pypi
> pyparsing                 3.1.4                    pypi_0    pypi
> pyproj                    3.7.0                    pypi_0    pypi
> python                    3.10.15         h4a871b0_1_cpython    conda-forge
> python-dateutil           2.9.0.post0              pypi_0    pypi
> pytorch-lightning         2.4.0                    pypi_0    pypi
> pytz                      2024.2                   pypi_0    pypi
> pyyaml                    6.0.2                    pypi_0    pypi
> rapids-dask-dependency    24.10.0                  pypi_0    pypi
> readline                  8.2                  h8228510_1    conda-forge
> requests                  2.32.3                   pypi_0    pypi
> rmm-cu12                  24.4.0                   pypi_0    pypi
> rtree                     1.3.0                    pypi_0    pypi
> scanpy                    1.10.3                   pypi_0    pypi
> scikit-image              0.24.0                   pypi_0    pypi
> scikit-learn              1.5.2                    pypi_0    pypi
> scipy                     1.14.1                   pypi_0    pypi
> seaborn                   0.13.2                   pypi_0    pypi
> segger                    0.1.0                    pypi_0    pypi
> session-info              1.0.0                    pypi_0    pypi
> setuptools                75.1.0             pyhd8ed1ab_0    conda-forge
> shapely                   2.0.6                    pypi_0    pypi
> six                       1.16.0                   pypi_0    pypi
> slicerator                1.1.0                    pypi_0    pypi
> sortedcontainers          2.4.0                    pypi_0    pypi
> squidpy                   1.2.0                    pypi_0    pypi
> statsmodels               0.14.4                   pypi_0    pypi
> stdlib-list               0.10.0                   pypi_0    pypi
> sympy                     1.13.3                   pypi_0    pypi
> tblib                     3.0.0                    pypi_0    pypi
> texttable                 1.7.0                    pypi_0    pypi
> threadpoolctl             3.5.0                    pypi_0    pypi
> tifffile                  2024.9.20                pypi_0    pypi
> tk                        8.6.13          noxft_h4845f30_101    conda-forge
> toolz                     1.0.0                    pypi_0    pypi
> torch                     2.4.1                    pypi_0    pypi
> torch-geometric           2.6.1                    pypi_0    pypi
> torchmetrics              1.4.3                    pypi_0    pypi
> torchvision               0.19.1                   pypi_0    pypi
> tornado                   6.4.1                    pypi_0    pypi
> tqdm                      4.66.5                   pypi_0    pypi
> triton                    3.0.0                    pypi_0    pypi
> typeguard                 4.3.0                    pypi_0    pypi
> typing-extensions         4.12.2                   pypi_0    pypi
> tzdata                    2024.2                   pypi_0    pypi
> umap-learn                0.5.6                    pypi_0    pypi
> urllib3                   2.2.3                    pypi_0    pypi
> validators                0.34.0                   pypi_0    pypi
> wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
> wrapt                     1.16.0                   pypi_0    pypi
> xarray                    2024.9.0                 pypi_0    pypi
> xz                        5.2.6                h166bdaf_0    conda-forge
> yarl                      1.15.0                   pypi_0    pypi
> zarr                      2.18.3                   pypi_0    pypi
> zict                      3.0.0                    pypi_0    pypi
> zipp                      3.20.2                   pypi_0    pypi`

**Additional context**

**Comment by EliHei2** [comment]
could you use `segger.prediction.predict_parquet` instead of `segger.prediction.predict`? 
you can follow the instructions here: https://elihei2.github.io/segger_dev/notebooks/segger_tutorial/#32-faster-prediction-with-segger

also you can set `knn_algorithm = 'cuda'`.
